# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - directory: "/go-gin" # Location of package manifests
    package-ecosystem: "gomod" # See documentation for possible values  
    schedule:
      interval: "weekly"

  - directory: "/java-spark"
    package-ecosystem: "maven"
    schedule:
      interval: "weekly"

  - directory: "/java-spring"
    package-ecosystem: "gradle"
    schedule:
      interval: "weekly"

  - directory: "/nodejs-express"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"

  - directory: "/php-slim"
    package-ecosystem: "composer"
    schedule:
      interval: "weekly"

  - directory: "/python-flask"
    package-ecosystem: "pip"
    schedule:
      interval: "weekly"
