name: Python / Flask

on:
  pull_request:
    branches: ~
    paths:
    - '.github/workflows/test-python-flask.yml'
    - 'python-flask/**'
    - 'requirements.txt'
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/test-python-flask.yml'
    - 'python-flask/**'
    - 'requirements.txt'

  # Allow job to be triggered manually.
  workflow_dispatch:

  # Run job each night after CrateDB nightly has been published.
  schedule:
    - cron: '0 3 * * *'

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: "
     Python: ${{ matrix.python-version }}
     CrateDB: ${{ matrix.cratedb-version }}
     on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        python-version: [
          '3.12',
          '3.13',
          '3.14',
        ]
        cratedb-version: [ 'nightly' ]

    steps:

      - name: Acquire sources
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: 'true'
          cache-dependency-glob: |
            python-flask/pyproject.toml
          cache-suffix: ${{ matrix.python-version }}
          enable-cache: 'true'
          python-version: ${{ matrix.python-version }}

      - name: Validate python-flask
        run: |

          # Somehow broken as of 2026-04?
          # TODO: Please report to `pyveci/pueblo` on GitHub.
          # uvx --from=pueblo --with="poethepoet<0.43" ngr test python-flask

          # Workaround.
          cd python-flask
          uv pip install '.[develop]'
          poe check
