name: Go

on:
  pull_request:
    branches: ~
    paths:
    - '.github/workflows/test-go.yml'
    - 'go-gin/**'
    - 'requirements.txt'
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/test-go.yml'
    - 'go-gin/**'
    - 'requirements.txt'

  # Allow job to be triggered manually.
  workflow_dispatch:

  # Run job each night after CrateDB nightly has been published.
  schedule:
    - cron: '0 3 * * *'

# Cancel in-progress jobs when pushing to the same branch.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: "
     Go: ${{ matrix.go-version }}
     CrateDB: ${{ matrix.cratedb-version }}
     on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        go-version: [ '1.20.x', '1.21.x' ]
        cratedb-version: [ 'nightly' ]

    steps:

      - name: Acquire sources
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install utilities
        run: |
          pip install -r requirements.txt

      - name: Validate go-gin
        run: |
          ngr test --accept-no-venv go-gin
